### PR TITLE
"Add Euphoria logo to about phone. Thanks to BeanStalk

### PR DESCRIPTION
**Pull request by fezzy102**
commits i just kanged to Euphoria edited the png. and
files to work on Ephoria.
https://drive.google.com/file/d/0B23ZIeRp4mZOUERYTUJ5UDlncGM/view?usp=sharing"

### CODE REVIEW

**Comment by Altaf-Mahdi** [comment]
Hey, I'm going to push this to our gerrit, would you know who the original author is?

**Comment by fezzy102** [comment]
Scott hartbti from beanstalk ROM.

**Comment by Altaf-Mahdi** [comment]
http://eosgerrit.ddns.net:51250/#/c/6105/

**Comment by 0xnth** [comment]
@Altaf-Mahdi, why not add Logo EuphoriaOS in Statusbar?

**Pull request closed without merging**
