### PR TITLE
Update cm_strings.xml

### PR DESCRIPTION
**Pull request by YassGo**
Added Missing Capital Letters

### CODE REVIEW

**Comment by Altaf-Mahdi** [comment]
Thanks for the pull, @RenaudR is taking care of French translations so if you have any issues just contact him, if there's more than one person translating the same language we will have conflicts.

**Comment by RenaudR** [comment]
Hello and thank you I totally agree, the error was corrected already, he just had to wait Madhi merges requests.

**Comment by RenaudR** [comment]
@Altaf-Mahdi  How can I contact?
There are still three files to be merged

https://github.com/Euphoria-OS/android_packages_apps_Settings/pull/47
https://github.com/Euphoria-OS/android_packages_apps_Settings/pull/46
https://github.com/Euphoria-OS/android_packages_apps_Settings/pull/42

Is it possible to integrate myself as a translator on the Euphoria, I can merge my own translation, would be easier because it puts late translations and are missing in the new versions.

I sent you an email on your Gmail.

**Comment by Altaf-Mahdi** [comment]
@RenaudR I just replied to your email

**Comment by YassGo** [comment]
Ok Guys I'll let you work :)

**Pull request closed without merging**
